### ISSUE TITLE
The vignette breaks at the prepare_tables call

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/neighbouRhood#3]
I ran this to test the package:

```{r}
fn_cells = system.file("extdata", "cell.csv", package = "neighbouRhood", mustWork = TRUE)
fn_relationship = system.file("extdata", "Object relationships.csv", package = "neighbouRhood", mustWork = TRUE)
dat_cells[, label := sample.int(10, size=.N, replace = T)]
dat_cells[, group := ImageNumber]
d = prepare_tables(dat_cells, dat_relation)
```

the `prepare_tables` function returns this error:

> Error in `:=`(label, as.factor(label)) : 
  Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").
In addition: Warning messages:
1: You are using a dplyr method on a raw data.table, which will call the data frame implementation, and is likely to be inefficient.
To suppress this message, either generate a data.table translation with `lazy_dt()` or convert to a data frame or tibble with `as.data.frame()`/`as_tibble()`. 
2: You are using a dplyr method on a raw data.table, which will call the data frame implementation, and is likely to beinefficient.
To suppress this message, either generate a data.table translation with `lazy_dt()` or convert to a data frame or tibble
with `as.data.frame()`/`as_tibble()`.

So specifically, the `prepare_tables` function breaks here:

https://github.com/BodenmillerGroup/neighbouRhood/blob/6bee8c8e9d97507b6bc77cea6598e5de31ac9018/R/neighbouRhood.R#L126

**Comment by votti** [comment]
Hey @nilseling,
This seems to be dependent on the exact dplyr/data.table version installed :/ 
Could you post your `sessionInfo` so I can reproduce your issue?

**Comment by nilseling** [comment]
Yep, sessionInfo is:

>R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin18.6.0 (64-bit)
Running under: macOS Mojave 10.14.6
Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.7/lib/libopenblasp-r0.3.7.dylib
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] RColorBrewer_1.1-2  gplots_3.0.1.1      neighbouRhood_0.1.0 ggplot2_3.2.1       dtplyr_1.0.0        magrittr_1.5       
[7] dplyr_0.8.3         data.table_1.12.6  
loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3         rstudioapi_0.10    tidyselect_0.2.5   munsell_0.5.0      colorspace_1.4-1   R6_2.4.1           rlang_0.4.2       
 [8] caTools_1.17.1.3   tools_3.6.1        grid_3.6.1         gtable_0.3.0       KernSmooth_2.23-16 withr_2.1.2        gtools_3.8.1      
[15] lazyeval_0.2.2     assertthat_0.2.1   tibble_2.1.3       lifecycle_0.1.0    crayon_1.3.4       purrr_0.3.3        bitops_1.0-6      
[22] glue_1.3.1         gdata_2.18.0       compiler_3.6.1     pillar_1.4.2       scales_1.1.0       pkgconfig_2.0.3

**Comment by votti** [comment]
Just because your code snippet doesnt include it: did you read the data with `data.table::fread`?
```
dat_cells = fread(fn_cells)
dat_relation = fread(fn_relationship)
```

is:
```
 is.data.table(dat_cells) == TRUE
 is.data.table(dat_relation) == TRUE
```

**Comment by votti** [comment]
I just updated my `dplyr`/`data.table` and now also get the issue.
It seems to be a package version issue :(

**Comment by nilseling** [comment]
Could you still fix this? I want to implement this function for a `SingleCellExperiment` object, which is easier to maintain. But for this I'll need to check if it reproduces what the original implementation returns.

**Comment by votti** [comment]
I will look into it.

I was also using this mini project to play around with the latest features that should have allowed to combine dplyr+data.table - seeing how brittle this seems to be I guess this was not the best technology choice.

**Comment by votti** [comment]
I rewrote the code to not longer rely so much on dplyr but using standard `data.table`. This should make things less brittle. Please give it a try if it works now for you!

**Comment by nilseling** [comment]
Perfect, thanks!
