### ISSUE TITLE
Problems with the creation of the cell.csv and object-realationships.csv file

### ISSUE THREAD

**Issue by Joschuafriedel** [BodenmillerGroup/neighbouRhood#7]
Hello,
could you give me any documentation how you created the cell.csv and object-realationships.csv test-file in CellProfiler? 
Best regards
Joschua Friedel

**Comment by nilseling** [comment]
Hi @Joschuafriedel 

did you have a look at the [ImcSegmentationPipeline](https://github.com/BodenmillerGroup/ImcSegmentationPipeline)?
When following the pipeline, in the last step you export the cell-specific features (as well as image Id and cell Id) into the `cell.csv` file. The `Object relationships.csv` file contains edges between neighbouring cells (also defined within the pipeline).
So at the end what you need is this edge list.
Does that help?
Best,

Nils

**Comment by Joschuafriedel** [comment]
Thank you very much, it worked but now I have problems with reading my Data tables in R. Is it not enough to format both tables  as in the example? Unfortunately I can not see the formation of the test data in R. Or would it also be possible to pull the results of the neighborhood analysis out of the MatLab based HistoCAT analysis, as I would need them for the creation of a network graph
Best regards

**Comment by nilseling** [comment]
Hi, yes it would be enough to format the data as in the example. For `neighbouRhood` the test data are located [here](https://github.com/BodenmillerGroup/neighbouRhood/tree/master/inst/extdata).  When using `CellProfiler`, the network graph is already exported as the `Object relationships.csv` file. As for export of the neighbourhood analysis in HistoCAT, @JanaFischer could possibly answer this.

**Comment by nilseling** [comment]
Hey, please have a look at [read_cpout](https://bodenmillergroup.github.io/imcRtools/reference/read_cpout.html) and [testInteractions](https://bodenmillergroup.github.io/imcRtools/reference/testInteractions.html) for an updated version of the neighbourhood analysis.
